using cleansing;
using udf;

$companies_in = read from '../resources/govwild/input/OriginalFreebaseCompany.json';

// ---------------------------------------------------------
// SCRUBBING
// ---------------------------------------------------------
$companies_scrubbed = scrub $companies_in with rules {
	_id: [required, concat_strings("_L")],
	id: required,
	name: [required, extract_name("/home/tommy-neubert/Arbeitsfläche/Hiwi/Repositories/cleansing-example/examples/src/main/resources/govwild/scrub/organizationSuffix.dict")], //array_get(0), remove_all_characters("\'"), notContainedIn([""])],
	companyType: required?: default("normal company"),
	industry: required?: default(""),
	
	// places
	locations: required?: default([]),
	headquarters: required?: default([]),
	
	// legal entities
	subsidiaryCompanies: required?: default([]),
	parentCompany: [required, split(",")]?: default([]),
	companiesAcquired: required?: default([]),
	acquiredBy: required?: default(""),
	
	// persons
	advisors: required?: default([]),
	boardMembers: required?: default([]),
	founders: required?: default([])
};
// ---------------------------------------------------------
write $companies_scrubbed to '../resources/govwild/output/SCRUB_Companies.json';
// ---------------------------------------------------------

// ---------------------------------------------------------
// Entity Extraction
// ---------------------------------------------------------
//$companies_unrolled_sub = unroll $companies_scrubbed on "subsidiaryCompanies";
//$companies_unrolled_par = unroll $companies_scrubbed on "parentCompany";
// ---------------------------------------------------------
$companies = map entities of $c in $companies_scrubbed into [
	entity $companies identified by $c._id with {
		$c._id,
		$c.guid,
		$c.name,
		$c.companyType,
		$c.industry,
		$c.locations,
		$c.headquarters,
		$c.companiesAcquired,
		$c.acquiredBy,
		$c.advisors,
		$c.boardMembers,
		$c.founders,
		$c.subsidiaryCompanies,
		$c.parentCompany
	}
];
// ---------------------------------------------------------
write $companies to '../resources/govwild/output/FreebaseCompanies.json';
// ---------------------------------------------------------

//write $companies_shortened to '../resources/govwild/output/SCRUB_Companies.json';
