using cleansing;
using udf;

$companies_in = read from '../resources/govwild/input/OriginalFreebaseCompany.json';

// ---------------------------------------------------------
// SCRUBBING
// ---------------------------------------------------------
$companies_scrubbed = scrub $companies_in with rules {
	_id: [required, concat_strings("_L")],
	id: required,
	name: [required, extract_name("/home/tommy-neubert/Arbeitsfläche/Hiwi/Repositories/cleansing-example/examples/src/main/resources/govwild/scrub/organizationSuffix.dict")], //array_get(0), remove_all_characters("\'"), notContainedIn([""])],
	companyType: required?: default("normal company"),
	industry: required?: default(""),
	
	// places
	locations: required?: default([]),
	headquarters: required?: default([]),
	
	// legal entities
	subsidiaryCompanies: required?: default([]),
	parentCompany: required?: default(""),
	companiesAcquired: required?: default([]),
	acquiredBy: required?: default(""),
	
	// persons
	advisors: required?: default([]),
	boardMembers: required?: default([]),
	founders: required?: default([])
};
// ---------------------------------------------------------
//write $companies_scrubbed to '../resources/govwild/output/SCRUB_Companies.json';
// ---------------------------------------------------------
$companies_shortened = transform $c in $companies_scrubbed into {
	$c._id,
	$c.name
};
// ---------------------------------------------------------

write $companies_shortened to '../resources/govwild/output/SCRUB_Companies.json';
